apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      volumes:
      - name: pv0002
        persistentVolumeClaim:
          claimName: jenkins-home
      containers:
      - image: jenkins/jenkins:latest
        name: guestbook-ui
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: pv0002
          
